version: '3.8'

services:
  property_friends:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ../:/app
    entrypoint: ["/bin/bash"]
    stdin_open: true
    tty: true