name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  format-lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Build Docker image
      run: docker build -f docker/Dockerfile -t property-friends .
    
    - name: Run black formatting check
      run: |
        docker run --rm \
          --entrypoint="" \
          -v ${{ github.workspace }}:/app \
          property-friends \
          bash -c "cd property_friends && uv sync --extra dev && uv run black --check ."
    
    - name: Run mypy type checking
      run: |
        docker run --rm \
          --entrypoint="" \
          -v ${{ github.workspace }}:/app \
          property-friends \
          bash -c "cd property_friends && uv sync --extra dev && uv run mypy . --ignore-missing-imports"
    
    - name: Run pydocstyle docstring checking
      run: |
        docker run --rm \
          --entrypoint="" \
          -v ${{ github.workspace }}:/app \
          property-friends \
          bash -c "cd property_friends && uv sync --extra dev && uv run pydocstyle --convention=google src/"

  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Build Docker image
      run: docker build -f docker/Dockerfile -t property-friends .
    
    - name: Run tests in Docker
      run: |
        docker run --rm \
          --entrypoint="" \
          -v ${{ github.workspace }}:/app \
          property-friends \
          bash -c "cd property_friends && uv sync --extra dev && uv run pytest tests -v"