name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Build Docker image
      run: docker build -f docker/Dockerfile -t property-friends .
    
    - name: Run tests in Docker
      run: |
        docker run --rm \
          --entrypoint="" \
          -v ${{ github.workspace }}:/app \
          property-friends \
          bash -c "uv sync --extra dev && uv run pytest tests -v"